version: '3.8'

services:
  quantumleap-ai:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quantumleap.rule=Host(`localhost`)"
      - "traefik.http.services.quantumleap.loadbalancer.server.port=3000"