[build]
  # Build command for Next.js
  command = "npm run build"
  
  # Directory to publish (Next.js output)
  publish = ".next"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Next.js specific settings
  NEXT_TELEMETRY_DISABLED = "1"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API routes optimization
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache"

# Environment variables (these will be set in Netlify dashboard)
# NEXT_PUBLIC_ALPHA_VANTAGE_API_KEY
# NEXT_PUBLIC_FINNHUB_API_TOKEN  
# NEXT_PUBLIC_TWELVE_DATA_API_KEY
# NEXT_PUBLIC_POLYGON_API_KEY